In [1]:
import model
import data

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
train_dataset = data.InverseData(mat_file="../Data/NEDC_lite.mat", outputs_npy="../Data/outputs_train.npy", ks_npy="../Data/ks_train.npy")
val_dataset = data.InverseData(mat_file="../Data/NEDC_lite.mat", outputs_npy="../Data/outputs_val.npy", ks_npy="../Data/ks_val.npy")
test_dataset = data.InverseData(mat_file="../Data/NEDC_lite.mat", outputs_npy="../Data/outputs_test.npy", ks_npy="../Data/ks_test.npy")


In [8]:
m = model.MLP([10, 64, 64, 64, 6])

weights = torch.load("./models/best_model.pth")

m.load_state_dict(weights)
m = m.to(device)

In [9]:
test_index = 0

In [10]:
train_dataset[0][0].shape

torch.Size([10])

In [15]:
outs = []
targets = []
for _ in range(11993):
    outs += [m(train_dataset[_][0])]
    targets += [train_dataset[_][1]]

In [17]:
outs

[tensor([0.5896, 0.5555, 0.7243, 0.7138, 0.7093, 0.6068],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5895, 0.5555, 0.7240, 0.7135, 0.7090, 0.6067],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5894, 0.5555, 0.7240, 0.7135, 0.7089, 0.6067],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5894, 0.5554, 0.7239, 0.7134, 0.7089, 0.6066],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5894, 0.5554, 0.7239, 0.7135, 0.7089, 0.6066],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5894, 0.5554, 0.7239, 0.7134, 0.7088, 0.6066],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5894, 0.5554, 0.7239, 0.7134, 0.7089, 0.6066],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5894, 0.5554, 0.7239, 0.7134, 0.7089, 0.6066],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5895, 0.5555, 0.7241, 0.7136, 0.7091, 0.6067],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5895, 0.5555, 0.7241, 0.7136, 0.7091, 0.6067],
        grad_fn=<SigmoidBackward0>),
 tensor([0.5895, 0.5555, 0.7241, 0.7137, 0.7091, 0

In [18]:
targets

[tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]