In [1]:
import model
import data

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
train_dataset = data.InverseData(mat_file="../Data/NEDC_lite.mat", outputs_npy="../Data/outputs_train.npy", ks_npy="../Data/ks_train.npy")
val_dataset = data.InverseData(mat_file="../Data/NEDC_lite.mat", outputs_npy="../Data/outputs_val.npy", ks_npy="../Data/ks_val.npy")
test_dataset = data.InverseData(mat_file="../Data/NEDC_lite.mat", outputs_npy="../Data/outputs_test.npy", ks_npy="../Data/ks_test.npy")


In [4]:
m = model.MLP([10, 64, 64, 64, 6])

weights = torch.load("./models/best_model.pth")

m.load_state_dict(weights)
m = m.to(device)

In [5]:
test_index = 0

In [6]:
train_dataset[0][0].shape

torch.Size([10])

In [7]:
outs = []
targets = []
for _ in range(11993):
    outs += [m(train_dataset[_][0])]
    targets += [train_dataset[_][1]]

In [8]:
import json



In [9]:
def denorm(norm_params_path, model_output):

    with open(norm_params_path) as f:
        norm_params = json.load(f)

    data = torch.zeros_like(model_output)
    print(data.shape)
    for n in norm_params:
        MAX = norm_params[n]['max']
        MIN = norm_params[n]['min']
        data[:,norm_params[n]['index']] = model_output[:,norm_params[n]['index']] * (MAX - MIN) + MIN

    return data

In [10]:
outs_stack = torch.stack(outs)
outs_stack

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], grad_fn=<StackBackward0>)

In [11]:
outs_stack[:,0]

tensor([1., 1., 1.,  ..., 1., 1., 1.], grad_fn=<SelectBackward0>)

In [12]:
outs_stack

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], grad_fn=<StackBackward0>)

[tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]),
 tensor([0.2617, 0.3716, 0.9373, 0.7747, 0.6464, 0.5430]